apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
spec:
  selector:
    matchLabels:
      app: app-1
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: app-1
        image: nicolaka/netshoot:latest
        args: ['/bin/sh', '-c', 'i=0; while true; do echo “$i: Test-Log”; i=$((i+1)); sleep 5; done']