cloud:
  provider: "aws" # must be aws or hetzner
  aws_access_key_id: "AWS-ACCESS-KEY" #fill if provider aws
  aws_secret_access_key: "AWS-SECRET-ACCESS-KEY" #fill if provider aws
  aws_profile: "default" #fill if provider aws
  region: "us-east-2" #fill if provider aws
  hcloud_token: "HETZNER-CLOUD-TOKEN" #fill if provider Hetzner Cloud
instance:
  type: "t3a.xlarge" #set cloud provider specific values. For example t3.large for aws, cpx31 for Hetzner Cloud
  root_volume_size: 100 #fill if provider aws
  rook_volume_size: 100
gpu_worker:
  type: "g4dn.xlarge" #fill if provider is aws and if instance is gpu type
  ami_id: "ami-0612fe06dd0a45323" #fill if provider is aws and if instance is gpu type 
cluster:
  name: "dev-test"        
  kubernetes_version: "1.23.9"
  control_plane_vm_count: 1
cni:
  pod_cidr: "10.200.0.0/16"
  pod_gateway: "10.200.0.1"
  service_cidr: "10.201.0.0/16"


