cloud:
  provider: "hetzner" # must be aws or hetzner
  aws_access_key_id: "ACCESS-KEY" #fill if provider aws
  aws_secret_access_key: "SECRET-ACCESS-KEY" #fill if provider aws
  aws_profile: "default" #fill if provider aws
  region: "us-east-2" #fill if provider aws
  hcloud_token: "HETZNER-CLOUD-TOKEN" #fill if provider Hetzner Cloud
instance:
  type: "cpx31"
  root_volume_size: 100 #fill if provider aws
  rook_volume_size: 100
cluster:
  name: "dev-test"        
  kubernetes_version: "1.23.9"
cni:
  pod_cidr: "10.200.0.0/16"
  pod_gateway: "10.200.0.1"
  service_cidr: "10.201.0.0/16"
