controller:
  kind: DaemonSet
  hostPort:
    enabled: true
  nodeSelector: {"node-role.kubernetes.io/worker": "worker"}
  hostNetwork: true
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
defaultBackend:
  enabled: true
  nodeSelector: {"node-role.kubernetes.io/worker": "worker"}